name: Run Tests with Parameters
on:
  repository_dispatch:
    types: [run-tests]
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print received parameters
        run: |
          echo "Tag: ${{ github.event.client_payload.tag }}"
