name: Run Tests with Parameters
on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print received parameters
        run: |
          echo "Branch: ${{ github.event.client_payload.branch }}"
          echo "Tag: ${{ github.event.client_payload.tag }}"